"""Phase 1 production schema.

Revision ID: 20260719_0001
Revises:
Create Date: 2026-07-19
"""
from __future__ import annotations

from alembic import op

revision = "20260719_0001"
down_revision = None
branch_labels = None
depends_on = None

UPGRADE_SQL = [
    'CREATE EXTENSION IF NOT EXISTS pg_trgm',
    'CREATE TABLE admin_users (\n\tid UUID NOT NULL, \n\tusername VARCHAR(120) NOT NULL, \n\tpassword_hash TEXT NOT NULL, \n\tis_active BOOLEAN DEFAULT true NOT NULL, \n\tlast_login_at TIMESTAMP WITH TIME ZONE, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_admin_users PRIMARY KEY (id), \n\tCONSTRAINT uq_admin_username UNIQUE (username)\n)',
    "CREATE TABLE categories (\n\tid VARCHAR(64) NOT NULL, \n\tlabel_en VARCHAR(160) NOT NULL, \n\tlabel_ur VARCHAR(160) NOT NULL, \n\tcolor VARCHAR(7) NOT NULL, \n\tis_active BOOLEAN DEFAULT true NOT NULL, \n\tpriority SMALLINT DEFAULT '50' NOT NULL, \n\tdescription_en TEXT, \n\tdescription_ur TEXT, \n\tcontext_profile JSONB DEFAULT '{}'::jsonb NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_categories PRIMARY KEY (id), \n\tCONSTRAINT ck_categories_priority_range CHECK (priority BETWEEN 0 AND 100), \n\tCONSTRAINT ck_categories_hex_color CHECK (color ~ '^#[0-9A-Fa-f]{6}$')\n)",
    "CREATE TABLE model_registry (\n\tid UUID NOT NULL, \n\tpurpose VARCHAR(40) NOT NULL, \n\tmodel_name VARCHAR(300) NOT NULL, \n\trevision VARCHAR(160) NOT NULL, \n\truntime VARCHAR(80) NOT NULL, \n\tlicense_name VARCHAR(80) NOT NULL, \n\tis_active BOOLEAN DEFAULT false NOT NULL, \n\tconfig JSONB DEFAULT '{}'::jsonb NOT NULL, \n\tbenchmark JSONB DEFAULT '{}'::jsonb NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_model_registry PRIMARY KEY (id), \n\tCONSTRAINT ck_model_registry_purpose_allowed CHECK (purpose IN ('ocr_detection','ocr_recognition','translation','embedding','summarization','language_detection','classification')), \n\tCONSTRAINT uq_model_revision UNIQUE (purpose, model_name, revision)\n)",
    "CREATE TABLE outbox_events (\n\tid UUID NOT NULL, \n\tevent_type VARCHAR(120) NOT NULL, \n\taggregate_type VARCHAR(80) NOT NULL, \n\taggregate_id VARCHAR(160) NOT NULL, \n\tpayload JSONB NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tpublished_at TIMESTAMP WITH TIME ZONE, \n\tattempts INTEGER DEFAULT '0' NOT NULL, \n\tlast_error TEXT, \n\tCONSTRAINT pk_outbox_events PRIMARY KEY (id)\n)",
    "CREATE TABLE processing_jobs (\n\tid UUID NOT NULL, \n\tjob_type VARCHAR(80) NOT NULL, \n\tpayload JSONB NOT NULL, \n\tpriority SMALLINT DEFAULT '50' NOT NULL, \n\tstatus VARCHAR(20) DEFAULT 'queued' NOT NULL, \n\tavailable_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tleased_until TIMESTAMP WITH TIME ZONE, \n\tlease_owner VARCHAR(200), \n\tattempts INTEGER DEFAULT '0' NOT NULL, \n\tmax_attempts INTEGER DEFAULT '5' NOT NULL, \n\tdedup_key VARCHAR(300), \n\tlast_error TEXT, \n\tcompleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_processing_jobs PRIMARY KEY (id), \n\tCONSTRAINT ck_processing_jobs_status_allowed CHECK (status IN ('queued','running','succeeded','failed','dead_letter','cancelled')), \n\tCONSTRAINT ck_processing_jobs_priority_range CHECK (priority BETWEEN 0 AND 100), \n\tCONSTRAINT ck_processing_jobs_attempts_valid CHECK (attempts >= 0 AND max_attempts > 0)\n)",
    "CREATE TABLE scheduled_jobs (\n\tid UUID NOT NULL, \n\tname VARCHAR(160) NOT NULL, \n\tjob_type VARCHAR(80) NOT NULL, \n\tpayload JSONB DEFAULT '{}'::jsonb NOT NULL, \n\tinterval_seconds INTEGER NOT NULL, \n\tnext_run_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tlast_run_at TIMESTAMP WITH TIME ZONE, \n\tis_enabled BOOLEAN DEFAULT true NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_scheduled_jobs PRIMARY KEY (id), \n\tCONSTRAINT ck_scheduled_jobs_interval_positive CHECK (interval_seconds > 0), \n\tCONSTRAINT uq_scheduled_job_name UNIQUE (name)\n)",
    "CREATE TABLE sentences (\n\tid UUID NOT NULL, \n\toriginal_text TEXT NOT NULL, \n\tnormalized_text TEXT NOT NULL, \n\toriginal_language VARCHAR(12) NOT NULL, \n\tconfidence_score FLOAT NOT NULL, \n\texact_hash VARCHAR(64) NOT NULL, \n\tstory_fingerprint VARCHAR(128), \n\tcalendar_date DATE NOT NULL, \n\tfirst_seen_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tlast_seen_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\toccurrence_count INTEGER DEFAULT '1' NOT NULL, \n\tdedup_similarity_score FLOAT, \n\tdedup_decision JSONB DEFAULT '{}'::jsonb NOT NULL, \n\textracted_entities JSONB DEFAULT '{}'::jsonb NOT NULL, \n\treview_status VARCHAR(20) DEFAULT 'accepted' NOT NULL, \n\tsearch_document TSVECTOR GENERATED ALWAYS AS (to_tsvector('simple', coalesce(original_text, ''))) STORED NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_sentences PRIMARY KEY (id), \n\tCONSTRAINT ck_sentences_language_allowed CHECK (original_language IN ('en','ur','mixed','unknown')), \n\tCONSTRAINT ck_sentences_confidence_range CHECK (confidence_score BETWEEN 0 AND 1), \n\tCONSTRAINT ck_sentences_review_status_allowed CHECK (review_status IN ('accepted','needs_review','rejected')), \n\tCONSTRAINT uq_sentence_day_exact_hash UNIQUE (calendar_date, exact_hash)\n)",
    "CREATE TABLE streams (\n\tid UUID NOT NULL, \n\tchannel_name VARCHAR(160) NOT NULL, \n\tyoutube_url TEXT NOT NULL, \n\tis_active BOOLEAN DEFAULT true NOT NULL, \n\tstatus VARCHAR(24) DEFAULT 'offline' NOT NULL, \n\tframe_rate_fps FLOAT DEFAULT '0.5' NOT NULL, \n\tlast_seen_at TIMESTAMP WITH TIME ZONE, \n\tlast_frame_at TIMESTAMP WITH TIME ZONE, \n\treconnect_count_today INTEGER DEFAULT '0' NOT NULL, \n\tconsecutive_failures INTEGER DEFAULT '0' NOT NULL, \n\tconfig JSONB DEFAULT '{}'::jsonb NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_streams PRIMARY KEY (id), \n\tCONSTRAINT ck_streams_status_allowed CHECK (status IN ('live','reconnecting','offline','error','disabled')), \n\tCONSTRAINT ck_streams_fps_range CHECK (frame_rate_fps > 0 AND frame_rate_fps <= 10), \n\tCONSTRAINT uq_streams_youtube_url UNIQUE (youtube_url)\n)",
    "CREATE TABLE system_settings (\n\tkey VARCHAR(160) NOT NULL, \n\tvalue JSONB NOT NULL, \n\tdescription TEXT, \n\tis_secret BOOLEAN DEFAULT false NOT NULL, \n\tupdated_by VARCHAR(120) DEFAULT 'system' NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_system_settings PRIMARY KEY (key)\n)",
    'CREATE TABLE admin_audit_log (\n\tid UUID NOT NULL, \n\tadmin_user_id UUID, \n\taction VARCHAR(120) NOT NULL, \n\tentity_type VARCHAR(80) NOT NULL, \n\tentity_id VARCHAR(160), \n\tbefore_state JSONB, \n\tafter_state JSONB, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_admin_audit_log PRIMARY KEY (id), \n\tCONSTRAINT fk_admin_audit_log_admin_user_id_admin_users FOREIGN KEY(admin_user_id) REFERENCES admin_users (id) ON DELETE SET NULL\n)',
    "CREATE TABLE daily_summaries (\n\tid UUID NOT NULL, \n\tcategory_id VARCHAR(64) NOT NULL, \n\tcalendar_date DATE NOT NULL, \n\tsummary_text_en TEXT DEFAULT '' NOT NULL, \n\tsummary_text_ur TEXT DEFAULT '' NOT NULL, \n\tsource_sentence_count INTEGER DEFAULT '0' NOT NULL, \n\tsummarizer_model VARCHAR(300), \n\tsummarizer_revision VARCHAR(160), \n\tlast_updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tfinalized_at TIMESTAMP WITH TIME ZONE, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_daily_summaries PRIMARY KEY (id), \n\tCONSTRAINT uq_daily_summary_category_date UNIQUE (category_id, calendar_date), \n\tCONSTRAINT fk_daily_summaries_category_id_categories FOREIGN KEY(category_id) REFERENCES categories (id) ON DELETE RESTRICT\n)",
    "CREATE TABLE keywords (\n\tid UUID NOT NULL, \n\tcategory_id VARCHAR(64) NOT NULL, \n\tterm VARCHAR(300) NOT NULL, \n\tnormalized_term VARCHAR(300) NOT NULL, \n\tlanguage VARCHAR(2) NOT NULL, \n\tis_active BOOLEAN DEFAULT true NOT NULL, \n\tpriority VARCHAR(16) DEFAULT 'normal' NOT NULL, \n\tmatch_mode VARCHAR(16) DEFAULT 'phrase' NOT NULL, \n\trequires_context BOOLEAN DEFAULT false NOT NULL, \n\tcontext_terms TEXT[] DEFAULT ARRAY[]::text[] NOT NULL, \n\texcluded_terms TEXT[] DEFAULT ARRAY[]::text[] NOT NULL, \n\tadded_by VARCHAR(120) DEFAULT 'system' NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_keywords PRIMARY KEY (id), \n\tCONSTRAINT ck_keywords_language_allowed CHECK (language IN ('en','ur')), \n\tCONSTRAINT ck_keywords_priority_allowed CHECK (priority IN ('normal','high','critical')), \n\tCONSTRAINT ck_keywords_match_mode_allowed CHECK (match_mode IN ('exact','phrase')), \n\tCONSTRAINT uq_keyword_normalized UNIQUE (category_id, language, normalized_term), \n\tCONSTRAINT fk_keywords_category_id_categories FOREIGN KEY(category_id) REFERENCES categories (id) ON DELETE CASCADE\n)",
    "CREATE TABLE raw_ocr_text (\n\tid UUID NOT NULL, \n\tstream_id UUID NOT NULL, \n\tframe_timestamp TIMESTAMP WITH TIME ZONE NOT NULL, \n\traw_text TEXT NOT NULL, \n\tnormalized_text TEXT NOT NULL, \n\tconfidence_score FLOAT NOT NULL, \n\tocr_engine VARCHAR(80) NOT NULL, \n\tocr_model VARCHAR(300) NOT NULL, \n\tframe_sha256 VARCHAR(64) NOT NULL, \n\tperceptual_hash VARCHAR(64), \n\tframe_width INTEGER NOT NULL, \n\tframe_height INTEGER NOT NULL, \n\tregions JSONB DEFAULT '[]'::jsonb NOT NULL, \n\tprocessing_metadata JSONB DEFAULT '{}'::jsonb NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\texpires_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tCONSTRAINT pk_raw_ocr_text PRIMARY KEY (id), \n\tCONSTRAINT ck_raw_ocr_text_confidence_range CHECK (confidence_score BETWEEN 0 AND 1), \n\tCONSTRAINT ck_raw_ocr_text_frame_dimensions CHECK (frame_width > 0 AND frame_height > 0), \n\tCONSTRAINT fk_raw_ocr_text_stream_id_streams FOREIGN KEY(stream_id) REFERENCES streams (id) ON DELETE CASCADE\n)",
    "CREATE TABLE sentence_categories (\n\tsentence_id UUID NOT NULL, \n\tcategory_id VARCHAR(64) NOT NULL, \n\tclassification_score FLOAT NOT NULL, \n\tclassifier_version VARCHAR(200) NOT NULL, \n\tevidence JSONB DEFAULT '{}'::jsonb NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_sentence_categories PRIMARY KEY (sentence_id, category_id), \n\tCONSTRAINT ck_sentence_categories_score_range CHECK (classification_score BETWEEN 0 AND 1), \n\tCONSTRAINT fk_sentence_categories_sentence_id_sentences FOREIGN KEY(sentence_id) REFERENCES sentences (id) ON DELETE CASCADE, \n\tCONSTRAINT fk_sentence_categories_category_id_categories FOREIGN KEY(category_id) REFERENCES categories (id) ON DELETE RESTRICT\n)",
    'CREATE TABLE sentence_embeddings (\n\tid UUID NOT NULL, \n\tsentence_id UUID NOT NULL, \n\tmodel_name VARCHAR(300) NOT NULL, \n\tmodel_revision VARCHAR(160) NOT NULL, \n\tdimensions INTEGER NOT NULL, \n\tembedding_vector REAL[] NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_sentence_embeddings PRIMARY KEY (id), \n\tCONSTRAINT uq_sentence_embedding_model UNIQUE (sentence_id, model_name, model_revision), \n\tCONSTRAINT ck_sentence_embeddings_dimensions_positive CHECK (dimensions > 0), \n\tCONSTRAINT fk_sentence_embeddings_sentence_id_sentences FOREIGN KEY(sentence_id) REFERENCES sentences (id) ON DELETE CASCADE\n)',
    "CREATE TABLE stream_health_events (\n\tid UUID NOT NULL, \n\tstream_id UUID NOT NULL, \n\tstatus VARCHAR(24) NOT NULL, \n\toccurred_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\taverage_ocr_confidence FLOAT, \n\treconnect_count INTEGER DEFAULT '0' NOT NULL, \n\tdetail JSONB DEFAULT '{}'::jsonb NOT NULL, \n\tCONSTRAINT pk_stream_health_events PRIMARY KEY (id), \n\tCONSTRAINT ck_stream_health_events_status_allowed CHECK (status IN ('live','reconnecting','offline','error','recovered')), \n\tCONSTRAINT fk_stream_health_events_stream_id_streams FOREIGN KEY(stream_id) REFERENCES streams (id) ON DELETE CASCADE\n)",
    "CREATE TABLE translations (\n\tid UUID NOT NULL, \n\tsentence_id UUID NOT NULL, \n\tenglish_text TEXT, \n\turdu_text TEXT, \n\ttranslation_status VARCHAR(20) NOT NULL, \n\tsource_language VARCHAR(12) NOT NULL, \n\tmodel_en VARCHAR(300), \n\tmodel_ur VARCHAR(300), \n\tmodel_revision_en VARCHAR(160), \n\tmodel_revision_ur VARCHAR(160), \n\tquality_score FLOAT, \n\tfailure_reason TEXT, \n\tsearch_document TSVECTOR GENERATED ALWAYS AS (to_tsvector('simple', coalesce(english_text, '') || ' ' || coalesce(urdu_text, ''))) STORED NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_translations PRIMARY KEY (id), \n\tCONSTRAINT ck_translations_status_allowed CHECK (translation_status IN ('complete','partial','failed','not_required')), \n\tCONSTRAINT ck_translations_quality_range CHECK (quality_score IS NULL OR (quality_score BETWEEN 0 AND 1)), \n\tCONSTRAINT uq_translations_sentence_id UNIQUE (sentence_id), \n\tCONSTRAINT fk_translations_sentence_id_sentences FOREIGN KEY(sentence_id) REFERENCES sentences (id) ON DELETE CASCADE\n)",
    "CREATE TABLE alerts_log (\n\tid UUID NOT NULL, \n\tsentence_id UUID NOT NULL, \n\tkeyword_id UUID, \n\tseverity VARCHAR(16) NOT NULL, \n\ttriggered_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tacknowledged BOOLEAN DEFAULT false NOT NULL, \n\tacknowledged_at TIMESTAMP WITH TIME ZONE, \n\tacknowledged_by UUID, \n\tCONSTRAINT pk_alerts_log PRIMARY KEY (id), \n\tCONSTRAINT ck_alerts_log_severity_allowed CHECK (severity IN ('normal','high','critical')), \n\tCONSTRAINT fk_alerts_log_sentence_id_sentences FOREIGN KEY(sentence_id) REFERENCES sentences (id) ON DELETE CASCADE, \n\tCONSTRAINT fk_alerts_log_keyword_id_keywords FOREIGN KEY(keyword_id) REFERENCES keywords (id) ON DELETE SET NULL, \n\tCONSTRAINT fk_alerts_log_acknowledged_by_admin_users FOREIGN KEY(acknowledged_by) REFERENCES admin_users (id) ON DELETE SET NULL\n)",
    'CREATE TABLE daily_summary_sentences (\n\tdaily_summary_id UUID NOT NULL, \n\tsentence_id UUID NOT NULL, \n\tfolded_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_daily_summary_sentences PRIMARY KEY (daily_summary_id, sentence_id), \n\tCONSTRAINT fk_daily_summary_sentences_daily_summary_id_daily_summaries FOREIGN KEY(daily_summary_id) REFERENCES daily_summaries (id) ON DELETE CASCADE, \n\tCONSTRAINT fk_daily_summary_sentences_sentence_id_sentences FOREIGN KEY(sentence_id) REFERENCES sentences (id) ON DELETE RESTRICT\n)',
    "CREATE TABLE sentence_keywords (\n\tsentence_id UUID NOT NULL, \n\tkeyword_id UUID NOT NULL, \n\tmatch_type VARCHAR(20) NOT NULL, \n\tmatch_score FLOAT NOT NULL, \n\tmatched_text TEXT NOT NULL, \n\ttext_span JSONB DEFAULT '{}'::jsonb NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_sentence_keywords PRIMARY KEY (sentence_id, keyword_id), \n\tCONSTRAINT ck_sentence_keywords_score_range CHECK (match_score BETWEEN 0 AND 1), \n\tCONSTRAINT ck_sentence_keywords_match_type_allowed CHECK (match_type IN ('exact','normalized','contextual')), \n\tCONSTRAINT fk_sentence_keywords_sentence_id_sentences FOREIGN KEY(sentence_id) REFERENCES sentences (id) ON DELETE CASCADE, \n\tCONSTRAINT fk_sentence_keywords_keyword_id_keywords FOREIGN KEY(keyword_id) REFERENCES keywords (id) ON DELETE RESTRICT\n)",
    "CREATE TABLE sentence_sources (\n\tid UUID NOT NULL, \n\tsentence_id UUID NOT NULL, \n\tstream_id UUID NOT NULL, \n\traw_ocr_id UUID, \n\tfirst_seen_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tlast_seen_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\toccurrence_count INTEGER DEFAULT '1' NOT NULL, \n\tsource_text TEXT NOT NULL, \n\tCONSTRAINT pk_sentence_sources PRIMARY KEY (id), \n\tCONSTRAINT uq_sentence_source UNIQUE (sentence_id, stream_id), \n\tCONSTRAINT fk_sentence_sources_sentence_id_sentences FOREIGN KEY(sentence_id) REFERENCES sentences (id) ON DELETE CASCADE, \n\tCONSTRAINT fk_sentence_sources_stream_id_streams FOREIGN KEY(stream_id) REFERENCES streams (id) ON DELETE RESTRICT, \n\tCONSTRAINT fk_sentence_sources_raw_ocr_id_raw_ocr_text FOREIGN KEY(raw_ocr_id) REFERENCES raw_ocr_text (id) ON DELETE SET NULL\n)",
    'CREATE TABLE summary_facts (\n\tid UUID NOT NULL, \n\tdaily_summary_id UUID NOT NULL, \n\tfact_text_en TEXT NOT NULL, \n\tfact_text_ur TEXT NOT NULL, \n\tfact_hash VARCHAR(64) NOT NULL, \n\tmodel_name VARCHAR(300) NOT NULL, \n\tmodel_revision VARCHAR(160) NOT NULL, \n\tdimensions INTEGER NOT NULL, \n\tembedding_vector REAL[] NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_summary_facts PRIMARY KEY (id), \n\tCONSTRAINT uq_summary_fact_hash UNIQUE (daily_summary_id, fact_hash), \n\tCONSTRAINT ck_summary_facts_dimensions_positive CHECK (dimensions > 0), \n\tCONSTRAINT fk_summary_facts_daily_summary_id_daily_summaries FOREIGN KEY(daily_summary_id) REFERENCES daily_summaries (id) ON DELETE CASCADE\n)',
    'CREATE TABLE summary_fact_sources (\n\tsummary_fact_id UUID NOT NULL, \n\tsentence_id UUID NOT NULL, \n\tCONSTRAINT pk_summary_fact_sources PRIMARY KEY (summary_fact_id, sentence_id), \n\tCONSTRAINT fk_summary_fact_sources_summary_fact_id_summary_facts FOREIGN KEY(summary_fact_id) REFERENCES summary_facts (id) ON DELETE CASCADE, \n\tCONSTRAINT fk_summary_fact_sources_sentence_id_sentences FOREIGN KEY(sentence_id) REFERENCES sentences (id) ON DELETE RESTRICT\n)',
    'CREATE INDEX ix_categories_active_priority ON categories (is_active, priority)',
    'CREATE INDEX ix_model_registry_active_purpose ON model_registry (is_active, purpose)',
    'CREATE INDEX ix_outbox_aggregate ON outbox_events (aggregate_type, aggregate_id)',
    'CREATE INDEX ix_outbox_unpublished ON outbox_events (created_at) WHERE published_at IS NULL',
    'CREATE INDEX ix_processing_jobs_lease ON processing_jobs (status, leased_until)',
    "CREATE INDEX ix_processing_jobs_poll ON processing_jobs (status, available_at, priority) WHERE status = 'queued'",
    'CREATE INDEX ix_scheduled_jobs_due ON scheduled_jobs (is_enabled, next_run_at)',
    'CREATE INDEX ix_sentences_calendar_date_created ON sentences (calendar_date, created_at)',
    'CREATE INDEX ix_sentences_first_seen ON sentences (first_seen_at)',
    'CREATE INDEX ix_sentences_normalized_trgm ON sentences USING gin (normalized_text gin_trgm_ops)',
    'CREATE INDEX ix_sentences_search_document ON sentences USING gin (search_document)',
    'CREATE INDEX ix_sentences_story_fingerprint ON sentences (calendar_date, story_fingerprint)',
    'CREATE INDEX ix_streams_active_status ON streams (is_active, status)',
    'CREATE INDEX ix_admin_audit_created ON admin_audit_log (created_at)',
    'CREATE INDEX ix_daily_summaries_date_category ON daily_summaries (calendar_date, category_id)',
    'CREATE INDEX ix_keywords_category_active_language ON keywords (category_id, is_active, language)',
    'CREATE INDEX ix_keywords_normalized_term ON keywords (normalized_term)',
    'CREATE INDEX ix_raw_ocr_expires_at ON raw_ocr_text (expires_at)',
    'CREATE INDEX ix_raw_ocr_frame_hash ON raw_ocr_text (stream_id, frame_sha256)',
    'CREATE INDEX ix_raw_ocr_stream_frame_timestamp ON raw_ocr_text (stream_id, frame_timestamp)',
    'CREATE INDEX ix_sentence_categories_category_sentence ON sentence_categories (category_id, sentence_id)',
    'CREATE INDEX ix_sentence_embeddings_model ON sentence_embeddings (model_name, model_revision)',
    'CREATE INDEX ix_stream_health_stream_occurred ON stream_health_events (stream_id, occurred_at)',
    'CREATE INDEX ix_translations_english_trgm ON translations USING gin (english_text gin_trgm_ops)',
    'CREATE INDEX ix_translations_search_document ON translations USING gin (search_document)',
    'CREATE INDEX ix_translations_urdu_trgm ON translations USING gin (urdu_text gin_trgm_ops)',
    'CREATE INDEX ix_alerts_unacknowledged ON alerts_log (acknowledged, triggered_at)',
    'CREATE INDEX ix_daily_summary_sentences_sentence ON daily_summary_sentences (sentence_id)',
    'CREATE INDEX ix_sentence_keywords_keyword_sentence ON sentence_keywords (keyword_id, sentence_id)',
    'CREATE INDEX ix_sentence_sources_stream_first_seen ON sentence_sources (stream_id, first_seen_at)',
    'CREATE INDEX ix_summary_facts_summary_created ON summary_facts (daily_summary_id, created_at)',
]
DOWNGRADE_SQL = [
    'DROP TABLE IF EXISTS "summary_fact_sources" CASCADE',
    'DROP TABLE IF EXISTS "summary_facts" CASCADE',
    'DROP TABLE IF EXISTS "sentence_sources" CASCADE',
    'DROP TABLE IF EXISTS "sentence_keywords" CASCADE',
    'DROP TABLE IF EXISTS "daily_summary_sentences" CASCADE',
    'DROP TABLE IF EXISTS "alerts_log" CASCADE',
    'DROP TABLE IF EXISTS "translations" CASCADE',
    'DROP TABLE IF EXISTS "stream_health_events" CASCADE',
    'DROP TABLE IF EXISTS "sentence_embeddings" CASCADE',
    'DROP TABLE IF EXISTS "sentence_categories" CASCADE',
    'DROP TABLE IF EXISTS "raw_ocr_text" CASCADE',
    'DROP TABLE IF EXISTS "keywords" CASCADE',
    'DROP TABLE IF EXISTS "daily_summaries" CASCADE',
    'DROP TABLE IF EXISTS "admin_audit_log" CASCADE',
    'DROP TABLE IF EXISTS "system_settings" CASCADE',
    'DROP TABLE IF EXISTS "streams" CASCADE',
    'DROP TABLE IF EXISTS "sentences" CASCADE',
    'DROP TABLE IF EXISTS "scheduled_jobs" CASCADE',
    'DROP TABLE IF EXISTS "processing_jobs" CASCADE',
    'DROP TABLE IF EXISTS "outbox_events" CASCADE',
    'DROP TABLE IF EXISTS "model_registry" CASCADE',
    'DROP TABLE IF EXISTS "categories" CASCADE',
    'DROP TABLE IF EXISTS "admin_users" CASCADE',
]


def upgrade() -> None:
    for statement in UPGRADE_SQL:
        op.execute(statement)


def downgrade() -> None:
    for statement in DOWNGRADE_SQL:
        op.execute(statement)
