from __future__ import annotations

import json
import re
import unicodedata
from collections.abc import Iterator
from typing import Any

CATEGORY_DATA: list[dict[str, Any]] = json.loads(r'''[
  {
    "id": "judiciary",
    "label_en": "Judiciary & Legal System",
    "label_ur": "عدلیہ اور قانون",
    "color": "#7C3AED",
    "keywords_en": [
      "court",
      "courts",
      "verdict",
      "hearing",
      "judge",
      "judges",
      "lawyer",
      "lawyers",
      "advocate",
      "case",
      "cases",
      "bail",
      "acquittal",
      "acquitted",
      "conviction",
      "convicted",
      "appeal",
      "FIR",
      "arrest",
      "arrested",
      "warrant",
      "custody",
      "remand",
      "sentence",
      "sentenced",
      "supreme court",
      "high court",
      "session court",
      "anti-corruption court",
      "accountability court",
      "NAB",
      "NCA",
      "prosecution",
      "defendant",
      "plaintiff",
      "witness",
      "testimony",
      "contempt",
      "petition",
      "suo motu",
      "stay order",
      "injunction",
      "bench",
      "chief justice",
      "justice",
      "law",
      "legal",
      "illegal",
      "legislation",
      "ordinance",
      "amendment",
      "constitution",
      "constitutional"
    ],
    "keywords_ur": [
      "عدالت",
      "فیصلہ",
      "سماعت",
      "جج",
      "وکیل",
      "مقدمہ",
      "ضمانت",
      "بری",
      "سزا",
      "اپیل",
      "ایف آئی آر",
      "گرفتاری",
      "وارنٹ",
      "حراست",
      "ریمانڈ",
      "سپریم کورٹ",
      "ہائی کورٹ",
      "احتساب عدالت",
      "نیب",
      "نیکا",
      "قانون",
      "غیر قانونی",
      "آئین",
      "آئینی",
      "توہین عدالت",
      "درخواست",
      "سو موٹو",
      "حکم امتناعی",
      "بنچ",
      "چیف جسٹس",
      "مدعی",
      "مدعا علیہ",
      "گواہ",
      "شہادت",
      "قانون سازی",
      "آرڈیننس",
      "ترمیم",
      "انصاف"
    ]
  },
  {
    "id": "politics",
    "label_en": "Politics & Government",
    "label_ur": "سیاست اور حکومت",
    "color": "#DC2626",
    "keywords_en": [
      "parliament",
      "senate",
      "national assembly",
      "provincial assembly",
      "government",
      "opposition",
      "prime minister",
      "PM",
      "president",
      "governor",
      "chief minister",
      "CM",
      "minister",
      "ministry",
      "election",
      "elections",
      "vote",
      "voting",
      "ballot",
      "polling",
      "constituency",
      "MNA",
      "MPA",
      "party",
      "PTI",
      "PMLN",
      "PPP",
      "JUI",
      "MQM",
      "ANP",
      "BNP",
      "coalition",
      "alliance",
      "budget",
      "legislation",
      "policy",
      "foreign policy",
      "cabinet",
      "federal",
      "provincial",
      "no confidence",
      "resignation",
      "dissolution",
      "martial law",
      "emergency",
      "coup",
      "democracy",
      "dictatorship",
      "political",
      "politician",
      "leader",
      "leadership",
      "press conference",
      "statement",
      "announcement",
      "protest",
      "sit-in",
      "dharna",
      "jalsa",
      "rally"
    ],
    "keywords_ur": [
      "پارلیمنٹ",
      "سینیٹ",
      "قومی اسمبلی",
      "صوبائی اسمبلی",
      "حکومت",
      "اپوزیشن",
      "وزیر اعظم",
      "صدر",
      "گورنر",
      "وزیر اعلیٰ",
      "وزیر",
      "وزارت",
      "الیکشن",
      "ووٹ",
      "بیلٹ",
      "پولنگ",
      "حلقہ",
      "پارٹی",
      "اتحاد",
      "بجٹ",
      "پالیسی",
      "کابینہ",
      "تحریک عدم اعتماد",
      "استعفیٰ",
      "تحلیل",
      "ہنگامی حالت",
      "جمہوریت",
      "سیاست",
      "سیاستدان",
      "قائد",
      "قیادت",
      "پریس کانفرنس",
      "احتجاج",
      "دھرنا",
      "جلسہ",
      "ریلی",
      "وفاقی",
      "صوبائی",
      "اعلان",
      "بیان"
    ]
  },
  {
    "id": "weather",
    "label_en": "Weather & Natural Disasters",
    "label_ur": "موسم اور قدرتی آفات",
    "color": "#0EA5E9",
    "keywords_en": [
      "rain",
      "rains",
      "rainfall",
      "heavy rain",
      "monsoon",
      "flood",
      "floods",
      "flooding",
      "flash flood",
      "storm",
      "thunderstorm",
      "hailstorm",
      "hail",
      "cyclone",
      "tornado",
      "hurricane",
      "dust storm",
      "heatwave",
      "heat wave",
      "temperature",
      "cold wave",
      "fog",
      "smog",
      "drought",
      "landslide",
      "earthquake",
      "tremor",
      "magnitude",
      "Richter",
      "snow",
      "snowfall",
      "blizzard",
      "weather forecast",
      "met office",
      "PMD",
      "alert",
      "warning",
      "emergency",
      "humidity",
      "wind speed",
      "cloudy",
      "sunny",
      "overcast",
      "visibility"
    ],
    "keywords_ur": [
      "بارش",
      "بھاری بارش",
      "مون سون",
      "سیلاب",
      "طوفان",
      "گرج چمک",
      "ژالہ باری",
      "اولے",
      "آندھی",
      "گرد وغبار",
      "ہیٹ ویو",
      "لو",
      "درجہ حرارت",
      "سردی",
      "کہرا",
      "سموگ",
      "خشک سالی",
      "لینڈ سلائیڈ",
      "زلزلہ",
      "برف باری",
      "موسمی الرٹ",
      "محکمہ موسمیات",
      "تنبیہ",
      "انتباہ",
      "بادل",
      "دھند",
      "طغیانی",
      "نمی",
      "ہوا"
    ]
  },
  {
    "id": "crime",
    "label_en": "Crime & Security",
    "label_ur": "جرائم اور سیکیورٹی",
    "color": "#EF4444",
    "keywords_en": [
      "bomb",
      "blast",
      "explosion",
      "attack",
      "terrorist",
      "terrorism",
      "militant",
      "extremist",
      "killed",
      "dead",
      "injured",
      "wounded",
      "casualties",
      "death toll",
      "firing",
      "gunfire",
      "shooting",
      "kidnapping",
      "abduction",
      "ransom",
      "murder",
      "robbery",
      "theft",
      "robbery",
      "dacoity",
      "police",
      "Rangers",
      "army",
      "security forces",
      "operation",
      "raid",
      "encounter",
      "TTP",
      "ISIS",
      "ISIL",
      "banned outfit",
      "militant group",
      "suicide attack",
      "weapon",
      "arms",
      "ammunition",
      "drugs",
      "narcotics",
      "smuggling",
      "missing person",
      "crime",
      "criminal",
      "wanted",
      "fugitive"
    ],
    "keywords_ur": [
      "بم",
      "دھماکہ",
      "حملہ",
      "دہشتگرد",
      "دہشتگردی",
      "عسکریت پسند",
      "ہلاک",
      "زخمی",
      "جاں بحق",
      "ہلاکتیں",
      "فائرنگ",
      "اغوا",
      "تاوان",
      "قتل",
      "ڈکیتی",
      "چوری",
      "پولیس",
      "رینجرز",
      "فوج",
      "سیکیورٹی فورسز",
      "آپریشن",
      "چھاپہ",
      "مقابلہ",
      "کالعدم تنظیم",
      "خودکش حملہ",
      "ہتھیار",
      "اسلحہ",
      "منشیات",
      "اسمگلنگ",
      "لاپتہ",
      "مجرم",
      "مطلوب",
      "فراری"
    ]
  },
  {
    "id": "economy",
    "label_en": "Economy & Finance",
    "label_ur": "معاشیات اور مالیات",
    "color": "#16A34A",
    "keywords_en": [
      "rupee",
      "dollar",
      "euro",
      "exchange rate",
      "currency",
      "inflation",
      "deflation",
      "CPI",
      "budget",
      "fiscal",
      "revenue",
      "tax",
      "income tax",
      "sales tax",
      "GST",
      "duty",
      "tariff",
      "IMF",
      "World Bank",
      "ADB",
      "loan",
      "debt",
      "bailout",
      "tranche",
      "GDP",
      "growth",
      "recession",
      "stock market",
      "KSE",
      "index",
      "shares",
      "investment",
      "FDI",
      "foreign exchange",
      "reserves",
      "export",
      "import",
      "trade deficit",
      "trade surplus",
      "balance of payment",
      "interest rate",
      "SBP",
      "State Bank",
      "monetary policy",
      "banking",
      "bank",
      "privatization",
      "fuel price",
      "petrol",
      "diesel",
      "electricity tariff",
      "utility bills",
      "subsidy",
      "unemployment",
      "jobs",
      "employment",
      "poverty"
    ],
    "keywords_ur": [
      "روپیہ",
      "ڈالر",
      "زر مبادلہ",
      "مہنگائی",
      "بجٹ",
      "ٹیکس",
      "آمدنی ٹیکس",
      "سیلز ٹیکس",
      "قرض",
      "آئی ایم ایف",
      "ورلڈ بینک",
      "ترقی",
      "کساد بازاری",
      "اسٹاک مارکیٹ",
      "کراچی اسٹاک ایکسچینج",
      "سرمایہ کاری",
      "برآمدات",
      "درآمدات",
      "تجارتی خسارہ",
      "سود کی شرح",
      "اسٹیٹ بینک",
      "مالیاتی پالیسی",
      "بینک",
      "نجکاری",
      "پٹرول",
      "ڈیزل",
      "بجلی",
      "گیس",
      "سبسڈی",
      "بے روزگاری",
      "غربت"
    ]
  },
  {
    "id": "health",
    "label_en": "Health & Medical",
    "label_ur": "صحت اور طب",
    "color": "#06B6D4",
    "keywords_en": [
      "hospital",
      "doctor",
      "patient",
      "disease",
      "illness",
      "epidemic",
      "pandemic",
      "outbreak",
      "dengue",
      "malaria",
      "typhoid",
      "cholera",
      "polio",
      "tuberculosis",
      "TB",
      "hepatitis",
      "covid",
      "corona",
      "coronavirus",
      "vaccine",
      "vaccination",
      "immunization",
      "medicine",
      "surgery",
      "operation",
      "treatment",
      "diagnosis",
      "health ministry",
      "WHO",
      "mental health",
      "cancer",
      "heart attack",
      "stroke",
      "blood pressure",
      "diabetes",
      "ambulance",
      "emergency",
      "ICU",
      "healthcare",
      "public health",
      "mortality",
      "infant mortality"
    ],
    "keywords_ur": [
      "اسپتال",
      "ڈاکٹر",
      "مریض",
      "بیماری",
      "وبا",
      "ڈینگی",
      "ملیریا",
      "ٹائیفائیڈ",
      "ہیضہ",
      "پولیو",
      "تپ دق",
      "ہیپاٹائٹس",
      "کورونا",
      "ویکسین",
      "ٹیکہ",
      "دوائی",
      "علاج",
      "تشخیص",
      "وزارت صحت",
      "عالمی ادارہ صحت",
      "ذہنی صحت",
      "کینسر",
      "دل کا دورہ",
      "بلڈ پریشر",
      "شوگر",
      "ایمبولینس",
      "ہنگامی",
      "آئی سی یو",
      "صحت عامہ"
    ]
  },
  {
    "id": "sports",
    "label_en": "Sports",
    "label_ur": "کھیل",
    "color": "#F59E0B",
    "keywords_en": [
      "cricket",
      "match",
      "test match",
      "ODI",
      "T20",
      "World Cup",
      "Asia Cup",
      "Champions Trophy",
      "PSL",
      "Pakistan Super League",
      "team",
      "squad",
      "captain",
      "player",
      "batsman",
      "bowler",
      "wicket",
      "century",
      "fifty",
      "innings",
      "victory",
      "defeat",
      "win",
      "loss",
      "draw",
      "PCB",
      "ICC",
      "BCCI",
      "umpire",
      "DRS",
      "stadium",
      "Lahore",
      "Karachi",
      "Rawalpindi",
      "football",
      "hockey",
      "squash",
      "kabaddi",
      "wrestling",
      "athletics",
      "Olympics",
      "Babar Azam",
      "Shaheen",
      "fitness",
      "injury",
      "selection",
      "tour",
      "series"
    ],
    "keywords_ur": [
      "کرکٹ",
      "میچ",
      "ٹیسٹ",
      "ون ڈے",
      "ٹی ٹوئنٹی",
      "عالمی کپ",
      "ایشیا کپ",
      "پی ایس ایل",
      "پاکستان سپر لیگ",
      "ٹیم",
      "کپتان",
      "کھلاڑی",
      "بلے باز",
      "گیند باز",
      "وکٹ",
      "سنچری",
      "پچاس",
      "اننگز",
      "فتح",
      "شکست",
      "پی سی بی",
      "آئی سی سی",
      "امپائر",
      "فٹ بال",
      "ہاکی",
      "اسکواش",
      "کبڈی",
      "کشتی",
      "اولمپکس"
    ]
  },
  {
    "id": "education",
    "label_en": "Education",
    "label_ur": "تعلیم",
    "color": "#8B5CF6",
    "keywords_en": [
      "university",
      "college",
      "school",
      "student",
      "students",
      "teacher",
      "professor",
      "examination",
      "exam",
      "result",
      "board",
      "matric",
      "intermediate",
      "FSC",
      "FA",
      "BA",
      "BSc",
      "MA",
      "MSc",
      "PhD",
      "degree",
      "admission",
      "merit list",
      "scholarship",
      "HEC",
      "BISE",
      "FDE",
      "fee",
      "tuition",
      "curriculum",
      "syllabus",
      "literacy",
      "dropout",
      "enrollment",
      "private school",
      "public school",
      "madrassa",
      "seminary",
      "cheating",
      "paper leak"
    ],
    "keywords_ur": [
      "یونیورسٹی",
      "کالج",
      "سکول",
      "طالب علم",
      "استاد",
      "پروفیسر",
      "امتحان",
      "نتیجہ",
      "بورڈ",
      "میٹرک",
      "انٹر",
      "ایف ایس سی",
      "بی اے",
      "ایم اے",
      "پی ایچ ڈی",
      "ڈگری",
      "داخلہ",
      "میرٹ لسٹ",
      "وظیفہ",
      "ایچ ای سی",
      "بیس",
      "تعلیم",
      "نصاب",
      "خواندگی",
      "سرکاری سکول",
      "پرائیویٹ سکول",
      "مدرسہ",
      "نقل",
      "پرچہ لیک"
    ]
  },
  {
    "id": "foreign",
    "label_en": "Foreign Affairs & International",
    "label_ur": "خارجہ امور",
    "color": "#64748B",
    "keywords_en": [
      "India",
      "China",
      "USA",
      "America",
      "United States",
      "UK",
      "Britain",
      "Afghanistan",
      "Iran",
      "Saudi Arabia",
      "UAE",
      "Turkey",
      "Bangladesh",
      "Russia",
      "Israel",
      "Palestine",
      "UN",
      "United Nations",
      "NATO",
      "SCO",
      "OIC",
      "SAARC",
      "embassy",
      "ambassador",
      "visa",
      "border",
      "LOC",
      "Durand Line",
      "diplomatic",
      "diplomacy",
      "bilateral",
      "sanction",
      "agreement",
      "treaty",
      "MOU",
      "trade deal",
      "foreign minister",
      "ceasefire",
      "tension",
      "war",
      "peace talks",
      "refugee",
      "deportation",
      "extradition"
    ],
    "keywords_ur": [
      "بھارت",
      "چین",
      "امریکہ",
      "برطانیہ",
      "افغانستان",
      "ایران",
      "سعودی عرب",
      "متحدہ عرب امارات",
      "ترکی",
      "روس",
      "اسرائیل",
      "فلسطین",
      "اقوام متحدہ",
      "نیٹو",
      "سفارت خانہ",
      "سفیر",
      "ویزہ",
      "سرحد",
      "لائن آف کنٹرول",
      "ڈیورنڈ لائن",
      "سفارتی",
      "معاہدہ",
      "ایم او یو",
      "وزیر خارجہ",
      "جنگ بندی",
      "کشیدگی",
      "جنگ",
      "مذاکرات",
      "مہاجر",
      "ملک بدر"
    ]
  },
  {
    "id": "energy",
    "label_en": "Energy & Infrastructure",
    "label_ur": "توانائی اور انفراسٹرکچر",
    "color": "#F97316",
    "keywords_en": [
      "electricity",
      "power",
      "load shedding",
      "loadshedding",
      "outage",
      "blackout",
      "WAPDA",
      "NEPRA",
      "gas",
      "LPG",
      "LNG",
      "SNGPL",
      "SSGC",
      "pipeline",
      "supply",
      "shortage",
      "capacity",
      "CPEC",
      "China Pakistan Economic Corridor",
      "motorway",
      "highway",
      "road",
      "bridge",
      "dam",
      "water",
      "irrigation",
      "Tarbela",
      "Mangla",
      "Diamer Bhasha",
      "reservoir",
      "solar",
      "wind",
      "nuclear",
      "renewable energy",
      "PAEC",
      "coal",
      "thermal",
      "hydro",
      "construction",
      "project",
      "infrastructure",
      "development"
    ],
    "keywords_ur": [
      "بجلی",
      "لوڈشیڈنگ",
      "بندش",
      "واپڈا",
      "نیپرا",
      "گیس",
      "ایل پی جی",
      "ایل این جی",
      "پائپ لائن",
      "قلت",
      "سی پیک",
      "موٹر وے",
      "شاہراہ",
      "سڑک",
      "پل",
      "ڈیم",
      "پانی",
      "آبپاشی",
      "ذخیرہ",
      "شمسی توانائی",
      "ہوا",
      "جوہری",
      "قابل تجدید توانائی",
      "کوئلہ",
      "تھرمل",
      "ہائیڈرو",
      "تعمیر",
      "منصوبہ",
      "انفراسٹرکچر",
      "ترقی"
    ]
  },
  {
    "id": "social",
    "label_en": "Human Rights & Social Issues",
    "label_ur": "انسانی حقوق اور سماجی مسائل",
    "color": "#EC4899",
    "keywords_en": [
      "human rights",
      "women rights",
      "child rights",
      "minority",
      "minorities",
      "discrimination",
      "harassment",
      "abuse",
      "violence",
      "domestic violence",
      "rape",
      "assault",
      "missing person",
      "protests",
      "workers rights",
      "labor",
      "bonded labor",
      "slavery",
      "trafficking",
      "poverty",
      "hunger",
      "homeless",
      "shelter",
      "welfare",
      "social protection",
      "HRCP",
      "Amnesty International",
      "press freedom",
      "journalist",
      "censorship",
      "transgender",
      "disability",
      "elderly",
      "orphan"
    ],
    "keywords_ur": [
      "انسانی حقوق",
      "خواتین کے حقوق",
      "بچوں کے حقوق",
      "اقلیت",
      "امتیازی سلوک",
      "ہراسانی",
      "تشدد",
      "گھریلو تشدد",
      "زیادتی",
      "لاپتہ",
      "احتجاج",
      "مزدور",
      "بندھوا مزدوری",
      "غلامی",
      "انسانی اسمگلنگ",
      "غربت",
      "بھوک",
      "بے گھر",
      "فلاح",
      "صحافت",
      "سنسر شپ",
      "صحافی",
      "خواجہ سرا",
      "معذوری",
      "یتیم"
    ]
  },
  {
    "id": "agriculture",
    "label_en": "Agriculture & Food",
    "label_ur": "زراعت اور خوراک",
    "color": "#84CC16",
    "keywords_en": [
      "wheat",
      "rice",
      "cotton",
      "sugarcane",
      "maize",
      "crop",
      "harvest",
      "yield",
      "agriculture",
      "farmer",
      "farming",
      "drought",
      "locust",
      "pest",
      "fertilizer",
      "pesticide",
      "food prices",
      "flour",
      "sugar",
      "cooking oil",
      "vegetable prices",
      "fruit prices",
      "food security",
      "famine",
      "shortage",
      "supply chain",
      "PASSCO",
      "procurement",
      "livestock",
      "poultry",
      "dairy",
      "fishery"
    ],
    "keywords_ur": [
      "گندم",
      "چاول",
      "کپاس",
      "گنا",
      "مکئی",
      "فصل",
      "کٹائی",
      "پیداوار",
      "زراعت",
      "کسان",
      "کاشتکاری",
      "خشک سالی",
      "ٹڈی دل",
      "کھاد",
      "کیڑے مار دوا",
      "خوراک کی قیمتیں",
      "آٹا",
      "چینی",
      "کھانے کا تیل",
      "سبزی",
      "پھل",
      "غذائی تحفظ",
      "قحط",
      "قلت",
      "پاسکو",
      "مویشی",
      "مرغبانی",
      "دودھ",
      "ماہی گیری"
    ]
  },
  {
    "id": "technology",
    "label_en": "Technology & Telecommunications",
    "label_ur": "ٹیکنالوجی اور مواصلات",
    "color": "#6366F1",
    "keywords_en": [
      "technology",
      "telecom",
      "telecommunications",
      "internet",
      "broadband",
      "mobile service",
      "PTA",
      "5G",
      "cyberattack",
      "cyber attack",
      "cybersecurity",
      "data breach",
      "digital payments",
      "fintech",
      "software",
      "artificial intelligence",
      "AI",
      "satellite",
      "space programme",
      "SUPARCO"
    ],
    "keywords_ur": [
      "ٹیکنالوجی",
      "ٹیلی کام",
      "مواصلات",
      "انٹرنیٹ",
      "براڈ بینڈ",
      "موبائل سروس",
      "پی ٹی اے",
      "فائیو جی",
      "سائبر حملہ",
      "سائبر سیکیورٹی",
      "ڈیٹا چوری",
      "ڈیجیٹل ادائیگی",
      "فن ٹیک",
      "سافٹ ویئر",
      "مصنوعی ذہانت",
      "سیٹلائٹ",
      "خلائی پروگرام",
      "سپارکو"
    ]
  },
  {
    "id": "transport",
    "label_en": "Transport & Aviation",
    "label_ur": "نقل و حمل اور ہوا بازی",
    "color": "#14B8A6",
    "keywords_en": [
      "railway",
      "railways",
      "train",
      "flight",
      "airline",
      "aviation",
      "PIA",
      "airport",
      "bus service",
      "metro bus",
      "BRT",
      "traffic",
      "road accident",
      "motorway closure",
      "port",
      "shipping",
      "public transport"
    ],
    "keywords_ur": [
      "ریلوے",
      "ٹرین",
      "پرواز",
      "ایئر لائن",
      "ہوا بازی",
      "پی آئی اے",
      "ہوائی اڈہ",
      "بس سروس",
      "میٹرو بس",
      "بی آر ٹی",
      "ٹریفک",
      "سڑک حادثہ",
      "موٹر وے بندش",
      "بندرگاہ",
      "جہاز رانی",
      "عوامی ٹرانسپورٹ"
    ]
  },
  {
    "id": "environment",
    "label_en": "Environment & Climate",
    "label_ur": "ماحولیات اور آب و ہوا",
    "color": "#22C55E",
    "keywords_en": [
      "climate change",
      "pollution",
      "air quality",
      "AQI",
      "deforestation",
      "wildlife",
      "conservation",
      "glacier",
      "emissions",
      "plastic waste",
      "environmental protection",
      "carbon emissions"
    ],
    "keywords_ur": [
      "موسمیاتی تبدیلی",
      "آلودگی",
      "فضائی معیار",
      "اے کیو آئی",
      "جنگلات کی کٹائی",
      "جنگلی حیات",
      "تحفظ ماحول",
      "گلیشیئر",
      "اخراج",
      "پلاسٹک فضلہ",
      "ماحولیاتی تحفظ",
      "کاربن اخراج"
    ]
  },
  {
    "id": "governance",
    "label_en": "Governance & Public Services",
    "label_ur": "حکمرانی اور عوامی خدمات",
    "color": "#A855F7",
    "keywords_en": [
      "NADRA",
      "passport office",
      "census",
      "local government",
      "municipal",
      "sanitation",
      "water supply",
      "public service",
      "bureaucracy",
      "civil service",
      "ombudsman",
      "e-governance",
      "public administration"
    ],
    "keywords_ur": [
      "نادرا",
      "پاسپورٹ دفتر",
      "مردم شماری",
      "مقامی حکومت",
      "بلدیاتی",
      "صفائی",
      "پانی کی فراہمی",
      "عوامی خدمت",
      "بیوروکریسی",
      "سول سروس",
      "محتسب",
      "ای گورننس",
      "عوامی انتظامیہ"
    ]
  }
]''')

CATEGORY_CONTEXT: dict[str, list[str]] = {
    "judiciary": ["court", "judge", "law", "legal", "case", "petition", "عدالت", "جج", "قانون", "مقدمہ"],
    "politics": ["government", "parliament", "minister", "election", "party", "حکومت", "پارلیمنٹ", "وزیر", "الیکشن", "پارٹی"],
    "weather": ["weather", "rain", "flood", "temperature", "storm", "موسم", "بارش", "سیلاب", "درجہ حرارت", "طوفان"],
    "crime": ["police", "attack", "arrest", "killed", "security", "پولیس", "حملہ", "گرفتاری", "ہلاک", "سیکیورٹی"],
    "economy": ["economy", "tax", "rupee", "market", "budget", "معیشت", "ٹیکس", "روپیہ", "مارکیٹ", "بجٹ"],
    "health": ["health", "hospital", "doctor", "patient", "disease", "صحت", "اسپتال", "ڈاکٹر", "مریض", "بیماری"],
    "sports": ["match", "team", "player", "cricket", "tournament", "میچ", "ٹیم", "کھلاڑی", "کرکٹ", "ٹورنامنٹ"],
    "education": ["education", "school", "university", "student", "exam", "تعلیم", "سکول", "یونیورسٹی", "طالب علم", "امتحان"],
    "foreign": ["foreign", "embassy", "border", "diplomatic", "international", "خارجہ", "سفارت", "سرحد", "سفارتی", "بین الاقوامی"],
    "energy": ["electricity", "gas", "power", "pipeline", "infrastructure", "بجلی", "گیس", "توانائی", "پائپ لائن", "انفراسٹرکچر"],
    "social": ["rights", "welfare", "harassment", "poverty", "journalist", "حقوق", "فلاح", "ہراسانی", "غربت", "صحافی"],
    "agriculture": ["crop", "farmer", "wheat", "fertilizer", "food", "فصل", "کسان", "گندم", "کھاد", "خوراک"],
    "technology": ["technology", "internet", "telecom", "cyber", "digital", "ٹیکنالوجی", "انٹرنیٹ", "ٹیلی کام", "سائبر", "ڈیجیٹل"],
    "transport": ["transport", "railway", "flight", "airport", "traffic", "ٹرانسپورٹ", "ریلوے", "پرواز", "ہوائی اڈہ", "ٹریفک"],
    "environment": ["environment", "climate", "pollution", "emissions", "wildlife", "ماحول", "آب و ہوا", "آلودگی", "اخراج", "جنگلی حیات"],
    "governance": ["governance", "public service", "municipal", "NADRA", "census", "حکمرانی", "عوامی خدمت", "بلدیاتی", "نادرا", "مردم شماری"],
}

AMBIGUOUS_TERMS = {
    "case", "cases", "statement", "announcement", "leader", "party", "minister", "emergency",
    "alert", "warning", "operation", "bank", "growth", "power", "supply", "shortage", "water",
    "project", "development", "team", "win", "loss", "draw", "result", "board", "injury",
    "agreement", "war", "border", "labor", "poverty", "traffic", "ہوا", "پانی", "ترقی", "منصوبہ",
    "بیان", "اعلان", "وزیر", "پارٹی", "نتیجہ", "بورڈ", "ٹیم", "فتح", "شکست", "آپریشن",
    "ہنگامی", "قلت", "غربت", "جنگ", "سرحد",
    "Lahore", "Karachi", "Rawalpindi", "selection", "tour", "series", "food",
    "لاہور", "کراچی", "راولپنڈی", "انتخاب", "دورہ", "سیریز", "خوراک"
}

CRITICAL_TERMS = {
    "suicide attack", "bomb", "blast", "earthquake", "flash flood", "terrorist attack",
    "خودکش حملہ", "بم", "دھماکہ", "زلزلہ", "طغیانی", "دہشتگردی"
}
HIGH_TERMS = CRITICAL_TERMS | {
    "flood", "cyclone", "heatwave", "killed", "missing person", "outbreak", "court verdict",
    "سیلاب", "طوفان", "ہیٹ ویو", "ہلاک", "لاپتہ", "وبا", "عدالتی فیصلہ"
}

KEYWORD_MATCH_POLICY: dict[str, bool] = {
    "exact_normalized_phrase_only": True,
    "fuzzy_matching": False,
    "misspelling_variants": False,
    "autocorrection": False,
}


_ARABIC_DIACRITICS = re.compile(r"[ؐ-ًؚ-ٰٟٴۖ-ۭ]")
_WHITESPACE = re.compile(r"\s+")


def normalize_term(value: str, language: str) -> str:
    text = unicodedata.normalize("NFKC", value).strip()
    text = text.replace("ـ", "")
    if language == "ur":
        text = _ARABIC_DIACRITICS.sub("", text)
        translation = str.maketrans({
            "أ": "ا", "إ": "ا", "آ": "ا", "ٱ": "ا",
            "ي": "ی", "ى": "ی", "ئ": "ی",
            "ك": "ک", "ة": "ہ", "ۀ": "ہ", "ؤ": "و",
        })
        text = text.translate(translation)
    else:
        text = text.casefold()
    return _WHITESPACE.sub(" ", text)


def category_seed_rows() -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for position, category in enumerate(CATEGORY_DATA):
        context = CATEGORY_CONTEXT.get(category["id"], [])
        rows.append({
            "id": category["id"],
            "label_en": category["label_en"],
            "label_ur": category["label_ur"],
            "color": category["color"],
            "priority": max(10, 90 - position * 3),
            "description_en": f"Context-aware monitoring for {category['label_en'].lower()}.",
            "description_ur": f"{category['label_ur']} سے متعلق سیاق و سباق پر مبنی نگرانی۔",
            "context_profile": {"positive_terms": context, "multi_label_allowed": True},
        })
    return rows


def _cross_category_normalized_terms() -> set[tuple[str, str]]:
    owners: dict[tuple[str, str], set[str]] = {}
    for category in CATEGORY_DATA:
        for language, key in (("en", "keywords_en"), ("ur", "keywords_ur")):
            for term in category[key]:
                identity = (language, normalize_term(term, language))
                owners.setdefault(identity, set()).add(category["id"])
    return {identity for identity, category_ids in owners.items() if len(category_ids) > 1}


def keyword_seed_rows() -> Iterator[dict[str, Any]]:
    seen: set[tuple[str, str, str]] = set()
    cross_category_terms = _cross_category_normalized_terms()
    for category in CATEGORY_DATA:
        category_id = category["id"]
        context = CATEGORY_CONTEXT.get(category_id, [])
        for language, key in (("en", "keywords_en"), ("ur", "keywords_ur")):
            for term in category[key]:
                normalized = normalize_term(term, language)
                identity = (category_id, language, normalized)
                if identity in seen:
                    continue
                seen.add(identity)
                priority = "critical" if normalized in {normalize_term(x, language) for x in CRITICAL_TERMS} else (
                    "high" if normalized in {normalize_term(x, language) for x in HIGH_TERMS} else "normal"
                )
                requires_context = (
                    normalized in {normalize_term(x, language) for x in AMBIGUOUS_TERMS}
                    or (language, normalized) in cross_category_terms
                )
                yield {
                    "category_id": category_id,
                    "term": term,
                    "normalized_term": normalized,
                    "language": language,
                    "priority": priority,
                    "match_mode": "phrase",
                    "requires_context": requires_context,
                    "context_terms": context if requires_context else [],
                    "excluded_terms": [],
                    "added_by": "phase-5-context-exact-seed",
                }
